# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7a35tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/COMPORG_PROJECT_backup/COMPORG_PROJECT.cache/wt [current_project]
set_property parent.project_path D:/COMPORG_PROJECT_backup/COMPORG_PROJECT.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths d:/SEU_CSE_507_user_uart_bmpg_1.3 [current_project]
set_property ip_output_repo d:/COMPORG_PROJECT_backup/COMPORG_PROJECT.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files d:/sce/prgmip32testcase1.coe
add_files d:/bry/test/dmem32case1t5.coe
add_files d:/bry/test/prgmip32case1t5.coe
add_files c:/Users/fizuf/Downloads/Minisys1Assemblerv2.2/output/prgmip32.coe
add_files c:/Users/fizuf/Downloads/Minisys1Assemblerv2.2/output/dmem32.coe
add_files d:/bry/test/prgmip32case1.coe
add_files d:/bry/test/dmem32case1.coe
add_files d:/bry/test/dmem32testcase1.coe
add_files d:/bry/test/prgmip32testcase1.coe
add_files d:/bry/test/prgmip32trimcase1.coe
add_files d:/bry/test/dmem32trimcase1.coe
add_files d:/bry/test/prgmip32.coe
add_files d:/bry/test/dmem32.coe
add_files d:/bry/test/dmem32marcase2.coe
add_files d:/bry/test/prgmip32marcase2.coe
add_files d:/bry/today/prgmip32.coe
add_files d:/bry/today/dmem32.coe
add_files d:/bry/today/prgmip32new.coe
add_files d:/bry/today/dmem32new.coe
add_files d:/bry/today/prgmip32scen1.coe
add_files d:/bry/today/dmem32scen1.coe
add_files d:/bry/today/prgmip32scen2.coe
add_files d:/bry/today/dmem32scen2.coe
add_files d:/bry/final/prgmip32testcase1.coe
add_files d:/bry/final/dmem32testcase1.coe
add_files d:/bry/final/prgmip321.coe
add_files d:/bry/final/dmem321.coe
add_files d:/bry/final/dmem32last1.coe
add_files d:/bry/final/prgmip32last1.coe
add_files d:/bry/new/prgmip32.coe
add_files d:/bry/new/dmem32.coe
add_files d:/bry/br/prgmip32.coe
add_files d:/bry/br/dmem32.coe
add_files d:/bry/final/dmem32scen2.coe
add_files d:/bry/final/prgmip32scen2.coe
add_files d:/bry/now/prgmip32.coe
add_files d:/bry/now/dmem32.coe
add_files {{d:/bry/just now/dmem32.coe}}
add_files {{d:/bry/just now/prgmip32.coe}}
add_files d:/bry/latest/prgmip32.coe
add_files d:/bry/latest/dmem32.coe
add_files d:/bry/sce/dmem32.coe
add_files d:/bry/sce/prgmip32.coe
read_verilog -library xil_defaultlib {
  D:/COMPORG_PROJECT_backup/COMPORG_PROJECT.srcs/sources_1/sevenseg/BCD_ctrl.v
  D:/COMPORG_PROJECT_backup/COMPORG_PROJECT.srcs/sources_1/sevenseg/BCD_to_Cathodes.v
  D:/COMPORG_PROJECT_backup/COMPORG_PROJECT.srcs/sources_1/new/Ifetc32.v
  D:/COMPORG_PROJECT_backup/COMPORG_PROJECT.srcs/sources_1/sevenseg/anode_ctrl.v
  D:/COMPORG_PROJECT_backup/COMPORG_PROJECT.srcs/sources_1/sevenseg/clock_divider_mileage.v
  D:/COMPORG_PROJECT_backup/COMPORG_PROJECT.srcs/sources_1/new/control32.v
  D:/COMPORG_PROJECT_backup/COMPORG_PROJECT.srcs/sources_1/new/decode32.v
  D:/COMPORG_PROJECT_backup/COMPORG_PROJECT.srcs/sources_1/new/dmemory32.v
  D:/COMPORG_PROJECT_backup/COMPORG_PROJECT.srcs/sources_1/new/executs32.v
  D:/COMPORG_PROJECT_backup/COMPORG_PROJECT.srcs/sources_1/new/freqdiv.v
  D:/COMPORG_PROJECT_backup/COMPORG_PROJECT.srcs/sources_1/sevenseg/refreshcounter.v
  D:/COMPORG_PROJECT_backup/COMPORG_PROJECT.srcs/sources_1/sevenseg/seven_seg_controller.v
  D:/COMPORG_PROJECT_backup/COMPORG_PROJECT.srcs/sources_1/sevenseg/top_mileage.v
  D:/COMPORG_PROJECT_backup/COMPORG_PROJECT.srcs/sources_1/new/CPU.v
}
read_ip -quiet D:/COMPORG_PROJECT_backup/COMPORG_PROJECT.srcs/sources_1/ip/RAM/RAM.xci
set_property used_in_implementation false [get_files -all d:/COMPORG_PROJECT_backup/COMPORG_PROJECT.srcs/sources_1/ip/RAM/RAM_ooc.xdc]

read_ip -quiet D:/COMPORG_PROJECT_backup/COMPORG_PROJECT.srcs/sources_1/ip/cpuclk/cpuclk.xci
set_property used_in_implementation false [get_files -all d:/COMPORG_PROJECT_backup/COMPORG_PROJECT.srcs/sources_1/ip/cpuclk/cpuclk_board.xdc]
set_property used_in_implementation false [get_files -all d:/COMPORG_PROJECT_backup/COMPORG_PROJECT.srcs/sources_1/ip/cpuclk/cpuclk.xdc]
set_property used_in_implementation false [get_files -all d:/COMPORG_PROJECT_backup/COMPORG_PROJECT.srcs/sources_1/ip/cpuclk/cpuclk_ooc.xdc]

read_ip -quiet D:/COMPORG_PROJECT_backup/COMPORG_PROJECT.srcs/sources_1/ip/prgrom/prgrom.xci
set_property used_in_implementation false [get_files -all d:/COMPORG_PROJECT_backup/COMPORG_PROJECT.srcs/sources_1/ip/prgrom/prgrom_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/COMPORG_PROJECT_backup/COMPORG_PROJECT.srcs/constrs_1/new/cons.xdc
set_property used_in_implementation false [get_files D:/COMPORG_PROJECT_backup/COMPORG_PROJECT.srcs/constrs_1/new/cons.xdc]


synth_design -top CPU -part xc7a35tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef CPU.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file CPU_utilization_synth.rpt -pb CPU_utilization_synth.pb"
